---
title: "CSE6424_Final_Dataprocessing"
output: html_document
---

```{r setup, message = FALSE, warning = FALSE}
library(tidymodels)
library(tidyverse) 
library(tidyquant)
library(timetk)
library(highcharter)
library(readxl)
library(corrr)
library(scales)
library(plotly)
library(haven) ## read_sas
library(readxl)
library(readstata13)
library(foreign)
require("survival")
library(survminer)
```

## RHS data downloaded from https://www.rand.org/well-being/social-and-behavioral-policy/centers/aging/dataprod/enhanced-fat.html
```{r}
load("HRS.rda")
## HHIDPN is individual ID
## R1AGEY_B is the age of respondent at 1992 interview
## RAGENDER is the gender of the response
## RAEDYRS is the years of education of the respondent
## RwMSTAT is the marriage status of respondent
## RwIWSTAT is the interview status of respondent, 0,1,4 indicates alive
## RwSHLT is the self-report of health of respondent
## RwOOPMD is the medical expenditure (out of pockects and totoal) of the respondent
## HwASTCK is the net value of stocks and mutual funds
## HwACHCK is the net value of checking, savings, and money market accounts
## HwACD is the net value of CDs, government savings bonds, and treasury bills
## HwABOND is the net value of bonds or bond funds
## HwAOTHR is the net value of all other savings
## HwADEBT is the net value of debt
## HwAHOUS is the net value of the Respondent’s primary residence
## HwARLES is the net value of real estate
## HwATRAN is the net value of vehicles
## HwABSNS is the net value of business
## HwAIRA is the net value of IRA/Keogh
## HwAMORT is the net value of all mortgages
## HwAHMLN is the sum of the reported or imputed value of all other home loans other than the first or second mortgages
## HwATOTN is Total Non-housing Wealth
## HwITOT is total household income
## HwATOTA is total household asset (excluding secondary residence)
## HwATOTF is net value of non-housing financial wealth
## Net value of  non-housing financial wealth = Sum (HwASTCK, HwACHCK, HwACD, HwABOND, HwAOTHR) - HwADEBT
## Total wealth = Sum (HwAHOUS, HwARLES, HwATRAN, HwABSNS, HwAIRA, HwASTCK, HwACHCK, HwACD, HwABOND,
## HwAOTHR) less Sum (HwAMORT, HwAHMLN, HwADEBT)
## Net value of non-housing wealth = Sum (HwARLES, HwATRAN, HwABSNS, HwAIRA, HwASTCK, HwACHCK, HwACD, HwABOND, HwAOTHR) less HwADEBT
## RwSAYRET is the self reported retired of the respondent
## RwCENREG is the Census region

c_AGEY_B<-NULL ## R1AGEY_B
c_MSTAT<-NULL ## RwMSTAT
c_IWSTAT<-NULL ## RwIWSTAT
c_SHLT<-NULL ## RwSHLT
c_OOPMD<-NULL ## RwOOPMD
c_ASTCK<-NULL ## HwASTCK
c_ACHCK<-NULL ## HwACHCK
c_ABOND <-NULL  ## HwABOND
c_ACD<-NULL ## HwACD
c_AOTHR<-NULL ## HwAOTHR
c_ADEBT<- NULL ## HwADEBT
c_AHOUS<-NULL ## HwAHOUS
c_ARLES<-NULL ## HwARLES 
c_ATRAN<-NULL ## HwATRAN
c_ABSNS <- NULL ## HwABSNS
c_AIRA <- NULL ## HwAIRA
c_AMORT <- NULL ## HwAMORT 
c_AHMLN <- NULL ## HwAHMLN
c_ATOTN <- NULL ## HwATOTN
c_ITOT<-NULL ## HwITOT
c_ATOTA<-NULL ## HwATOTA
c_ATOTF <- NULL ## HwATOTF
c_CENREG <-NULL ## RwCENREG
for (i in 1:13){
  c_AGEY_B<- rbind(c_AGEY_B, paste('R',i,'AGEY_B',sep=''))
  c_MSTAT <- rbind(c_MSTAT, paste('R',i,'MSTAT',sep=''))
  c_IWSTAT<-rbind(c_IWSTAT, paste('R',i,'IWSTAT',sep=''))
  c_SHLT <- rbind(c_SHLT, paste('R',i,'SHLT',sep=''))
  c_OOPMD <- rbind(c_OOPMD, paste('R',i,'OOPMD',sep=''))
  c_ASTCK <- rbind(c_ASTCK, paste('H',i,'ASTCK',sep=''))
  c_ACHCK <- rbind(c_ACHCK, paste('H',i,'ACHCK',sep=''))
  c_ACD <- rbind(c_ACD, paste('H',i,'ACD',sep=''))
  c_ABOND <- rbind(c_ABOND, paste('H',i,'ABOND',sep='') )
  c_AOTHR <- rbind(c_AOTHR, paste('H',i,'AOTHR',sep='') )
  c_ADEBT <- rbind(c_ADEBT,paste('H',i,'ADEBT',sep='') )
  c_AHOUS <- rbind(c_AHOUS, paste('H',i,'AHOUS',sep=''))
  c_ARLES <- rbind(c_ARLES, paste('H',i,'ARLES',sep=''))
  c_ATRAN <- rbind(c_ATRAN, paste('H',i,'ATRAN',sep=''))
  c_ABSNS <- rbind(c_ABSNS,paste('H',i,'ABSNS',sep=''))
  c_AIRA <- rbind(c_AIRA,paste('H',i,'AIRA',sep='') )
  c_AMORT <- rbind(c_AMORT, paste('H',i,'AMORT',sep='') )
  c_AHMLN <- rbind(c_AHMLN, paste('H',i,'AHMLN',sep='') )
  c_ATOTN <- rbind(c_ATOTN, paste('H',i,'ATOTN',sep='') )
  c_ITOT <- rbind(c_ITOT, paste('H',i,'ITOT',sep=''))
  c_ATOTA <- rbind(c_ATOTA, paste('H',i,'ATOTA',sep=''))
  c_ATOTF <- rbind(c_ATOTF, paste('H',i,'ATOTF',sep=''))
  c_CENREG <- rbind(c_CENREG, paste('R',i,'CENREG',sep=''))
}
c_OOPMD<-c_OOPMD[2:length(c_OOPMD)]


HRS_helathdata<-HRS %>%
  select(HHIDPN,R1AGEY_B,RAGENDER,RAEDYRS,
         c_MSTAT, c_IWSTAT, c_SHLT,c_OOPMD,c_ASTCK,c_ACHCK,c_ABOND,c_ACD,c_AOTHR,c_ADEBT,c_AHOUS,
         c_ARLES,c_ATRAN,c_ABSNS,c_AIRA,c_AMORT,c_AHMLN,c_ATOTN,c_ITOT,c_ATOTA, c_ATOTF,c_CENREG
  )%>%
  mutate(deadyear2=case_when(R1IWSTAT>4~1992,R2IWSTAT>4~1994,R3IWSTAT>4~1996,R4IWSTAT>4~1998,R5IWSTAT>4~2000,R6IWSTAT>4~2002,R7IWSTAT>4~2004,R8IWSTAT>4~2006,R9IWSTAT>4~2008,
        R10IWSTAT>4~2010,R11IWSTAT>4~2012,R12IWSTAT>4~2014,R13IWSTAT>4~2016))%>%
   mutate(deadyear2 = deadyear2-2)

write.csv(HRS_helathdata,file="DV_HRS.csv",row.names=FALSE)
```

## PSID data download from https://simba.isr.umich.edu/Zips/ZipMain.aspx
```{r}

######################### 2017 ################################
psid_data<-NULL
psid2017 <- read_sas("psid2017.sas7bdat" )
temp<-psid2017%>%
  select(ER66017,ER66003,ER68420,ER71445,ER71467,ER71481,ER71483,ER71293)%>%
  dplyr::rename(age=ER66017,state=ER66003, health=ER68420, stock=ER71445,medicaldebt=ER71467, house=ER71481, financialwealth=ER71483,labor=ER71293)%>%
  mutate(waveyear=2017)%>%
  select(age,state,health,stock,medicaldebt,house,financialwealth,labor,waveyear)
psid_data<-rbind(psid_data,temp)
rm(psid2017,temp)

########################## 2015 ###############################
psid2015 <- read_sas("psid2015.sas7bdat")
temp<-psid2015%>%
  select(ER60017,ER60003,ER62366,ER65368,ER65390,ER65404,ER65406,ER65021)%>%
  dplyr::rename(age=ER60017,state=ER60003, health=ER62366, stock=ER65368,medicaldebt=ER65390, house=ER65404, financialwealth=ER65406, labor=ER65021)%>%
  mutate(waveyear=2015)%>%
  select(age,state,health,stock,medicaldebt,house,financialwealth,labor,waveyear)
psid_data<-rbind(psid_data,temp)
rm(psid2015,temp)


########################## 2013 ###############################
psid2013 <- read_sas("psid2013.sas7bdat")
temp<-psid2013%>%
  select(ER53017,ER53003,ER55244,ER58171,ER58193,ER58207,ER58209,ER57841)%>%
  dplyr::rename(age=ER53017,state=ER53003, health=ER55244, stock=ER58171,medicaldebt=ER58193, house=ER58207, financialwealth=ER58209, labor=ER57841)%>%
  mutate(waveyear=2013)%>%
  select(age,state,health,stock,medicaldebt,house,financialwealth,labor,waveyear)
psid_data<-rbind(psid_data,temp)
rm(psid2013,temp)

########################## 2011 ###############################
psid2011 <- read_sas("psid2011.sas7bdat")
temp<-psid2011%>%
  select(ER47317,ER47303,ER49494,ER52358,ER52380,ER52390,ER52392,ER52085)%>%
  dplyr::rename(age=ER47317,state=ER47303, health=ER49494, stock=ER52358,medicaldebt=ER52380, house=ER52390, financialwealth=ER52392, labor=ER52085)%>%
  mutate(waveyear=2011)%>%
  select(age,state,health,stock,medicaldebt,house,financialwealth,labor,waveyear)
psid_data<-rbind(psid_data,temp)
rm(psid2011,temp)

######################### 2009 ################################
psid2009 <- read_sas("psid2009.sas7bdat")
temp<-psid2009%>%
  select(ER42017,ER42003,ER44175,ER46954,ER46971D3,ER46966,ER46968,ER46673)%>%
  dplyr::rename(age=ER42017,state=ER42003, health=ER44175, stock=ER46954,medicaldebt=ER46971D3, house=ER46966, financialwealth=ER46968, labor=ER46673)%>%
  mutate(waveyear=2009)%>%
  select(age,state,health,stock,medicaldebt,house,financialwealth,labor,waveyear)
psid_data<-rbind(psid_data,temp)
rm(psid2009,temp)

########################## 2007 ###############################
psid2007 <- read_sas("psid2007.sas7bdat") ### data has problem, recheck sas 
temp<-psid2007%>%
  select(ER41059,ER36017,ER36003,ER38202,ER40432,ER40686F1)%>%
  dplyr::rename(interviewid=ER41059, age=ER36017,state=ER36003, health=ER38202, medicaldebt=ER40432,labor=ER40686F1)%>%
  arrange(interviewid) ## Household ID
psid2007_2 <- read_sas("wlth2007er.sas7bdat") ### data has problem, recheck sas
temp2<-psid2007_2%>%
  select(S801,S811,S820,S816)%>%
  dplyr::rename(interviewid=S801,stock=S811, house=S820, financialwealth=S816)%>%
  arrange(interviewid) ## FAMILY ID
ttemp <- inner_join(temp,temp2,by=c("interviewid"))%>%
  mutate(waveyear=2007)%>%
  select(age,state,health,stock,medicaldebt,house,financialwealth,labor,waveyear)
psid_data<-rbind(psid_data,ttemp)
rm(psid2007,psid2007_2,temp,temp2,ttemp)


############################ 2005 #############################
psid2005 <- read_sas("psid2005.sas7bdat") ### data has problem, recheck sas 
temp<-psid2005%>%
  select(ER28069,ER25017,ER25003,ER26990,ER27257,ER27711F1)%>%
  dplyr::rename(interviewid=ER28069, age=ER25017,state=ER25003, health=ER26990, medicaldebt=ER27257,labor=ER27711F1)
psid2005_2 <- read_sas("wlth2005er.sas7bdat") ### data has problem, recheck sas
temp2<-psid2005_2%>%
  select(S701,S711,S720,S716)%>%
  dplyr::rename(interviewid=S701,stock=S711, house=S720, financialwealth=S716)
ttemp<-inner_join(temp,temp2,by=c("interviewid"))%>%
  mutate(waveyear=2005)%>%
  select(age,state,health,stock,medicaldebt,house,financialwealth,labor,waveyear)
psid_data<-rbind(psid_data,ttemp)
rm(psid2005,psid2005_2,temp,temp2,ttemp)

############################# 2003 ############################
psid2003 <- read_sas("psid2003.sas7bdat") ### data has problem, recheck sas 
temp<-psid2003%>%
  select(ER24170,ER21017,ER21003,ER23009,ER23297,ER23702F1)%>%
  dplyr::rename(interviewid=ER24170, age=ER21017,state=ER21003, health=ER23009, medicaldebt=ER23297,labor=ER23702F1)
psid2003_2 <- read_sas("wlth2003er.sas7bdat") ### data has problem, recheck sas
temp2<-psid2003_2%>%
  select(S601,S611,S620,S616)%>%
  dplyr::rename(interviewid=S601,stock=S611, house=S620, financialwealth=S616)
ttemp<-inner_join(temp,temp2,by=c("interviewid"))%>%
  mutate(waveyear=2003)%>%
  select(age,state,health,stock,medicaldebt,house,financialwealth,labor,waveyear)
psid_data<-rbind(psid_data,ttemp)
rm(psid2003,psid2003_2,temp,temp2,ttemp)

############################# 2001 ############################
psid2001 <- read_sas("psid2001.sas7bdat") ### data has problem, recheck sas 
temp<-psid2001%>%
  select(ER20393,ER17013,ER17004,ER19612,ER19860,ER20443)%>%
  dplyr::rename(interviewid=ER20393, age=ER17013,state=ER17004, health=ER19612, medicaldebt=ER19860,labor=ER20443)
psid2001_2 <- read_sas("wlth2001er.sas7bdat") ### data has problem, recheck sas
temp2<-psid2001_2%>%
  select(S501,S511,S520,S516)%>%
  dplyr::rename(interviewid=S501, stock=S511, house=S520, financialwealth=S516)
ttemp<-inner_join(temp,temp2,by=c("interviewid"))%>%
  mutate(waveyear=2001)%>%
  select(age,state,health,stock,medicaldebt,house,financialwealth,labor,waveyear)
psid_data<-rbind(psid_data,ttemp)
rm(psid2001,psid2001_2,temp,temp2,ttemp)


############################ 1999 #############################
psid1999 <- read_sas("psid1999.sas7bdat") ### data has problem, recheck sas 
temp<-psid1999%>%
  select(ER16447,ER13010,ER13004,ER15447,ER15799,ER16463)%>%
  dplyr::rename(interviewid=ER16447,age=ER13010,state=ER13004, health=ER15447, medicaldebt=ER15799,labor=ER16463)
psid1999_2 <- read_sas("wlth1999er.sas7bdat") ### data has problem, recheck sas
temp2<-psid1999_2%>%
  select(S401,S411,S420,S416)%>%
  dplyr::rename(interviewid=S401,stock=S411, house=S420, financialwealth=S416)
ttemp<-inner_join(temp,temp2,by=c("interviewid"))%>%
  mutate(waveyear=1999)%>%
  select(age,state,health,stock,medicaldebt,house,financialwealth,labor,waveyear)
psid_data<-rbind(psid_data,ttemp)
rm(psid1999,psid1999_2,temp,temp2,ttemp)


########################### 1994 ##############################
psid1994 <- read_sas("~/Dropbox/Shan_TDF/data/PSID/fam1994er/psid1994.sas7bdat") ### data has problem, recheck sas 
temp<-psid1994%>%
  select(ER4159R,ER2007,ER4156,ER3853,ER3753,ER4136)%>%
  dplyr::rename(interviewid=ER4159R,age=ER2007,state=ER4156, health=ER3853, medicaldebt=ER3753,labor=ER4136)
psid1994_2 <- read_sas("wlth1994er.sas7bdat") ### data has problem, recheck sas
temp2<-psid1994_2%>%
  select(S301,S311,S320,S316)%>%
  dplyr::rename(interviewid=S301,stock=S311, house=S320, financialwealth=S316)
ttemp<-inner_join(temp,temp2,by=c("interviewid"))%>%
  mutate(waveyear=1994)%>%
  select(age,state,health,stock,medicaldebt,house,financialwealth,labor,waveyear)
psid_data<-rbind(psid_data,ttemp)
rm(psid1994,psid1994_2,temp,temp2,ttemp)


saveRDS(psid_data,'cse6242_PSID.rda')
```


```{r}
HRS_helathdata<-read_csv("DV_HRS.csv")
Table_Age_Health_Wealth<-NULL
for (i in 2:13){
  temp <- HRS_helathdata%>%
   select(c(R1AGEY_B, deadyear2, paste('R',i,'SHLT',sep=''),paste('H',i,'ATOTF',sep=''),
            paste('H',i,'ITOT',sep=''), paste('H',i,'ATOTA',sep=''), paste('H',i,'ASTCK',sep=''),
            paste('R',i,'CENREG',sep=''), paste('R',i,'OOPMD',sep=''), HHIDPN))%>%
   dplyr::rename("age"="R1AGEY_B",
                 "Health"=paste('R',i,'SHLT',sep=''),
                 "NonhousingFinancialWealth"=paste('H',i,'ATOTF',sep=''),
                 "Income" = paste('H',i,'ITOT',sep=''),
                 "Totalwealth" = paste('H',i,'ATOTA',sep=''),
                 "Equity" = paste('H',i,'ASTCK',sep=''),
                 "region" = paste('R',i,'CENREG',sep=''),
                 "medicaldebt" = paste('R',i,'OOPMD',sep='')
                 ) %>%
      mutate(age = age  + (i-1)*2, health = case_when(Health<=3~0,TRUE~1),
             default=case_when(deadyear2<=(1992+2*(i-1))~1,TRUE~0))%>%
    select(region, age, default, health, HHIDPN,NonhousingFinancialWealth,Income,Totalwealth,Equity,medicaldebt)
  Table_Age_Health_Wealth <-rbind(Table_Age_Health_Wealth, temp)
}

temp<-Table_Age_Health_Wealth%>%
  mutate(age_indicator=case_when(age>19 & age<40 ~ "20~40", age>39 & age<50 ~ "40~50", age>49 & age<65 ~ "50~65",TRUE~"65+"))%>%
  dplyr::rename(financialwealth=NonhousingFinancialWealth, stock=Equity)%>%
  select(HHIDPN, age,age_indicator,health,stock,financialwealth,Totalwealth,Income,medicaldebt)

df<-temp%>%
  group_by(HHIDPN)%>%
  arrange(HHIDPN,age)%>%
  na.omit()%>%
  mutate(health_lag=lag(health), stock_lag = lag(stock), Totalwealth_lag=lag(Totalwealth), Income_lag=lag(Income),medicaldebt_lag=lag(medicaldebt))%>%
  select(HHIDPN,age,health,health_lag,stock_lag,Totalwealth_lag,Income_lag,medicaldebt_lag)%>%
  na.omit()%>%
  ungroup(HHIDPN)%>%
  select(-HHIDPN)

  
y<-df$health
x<-model.matrix(health~., df)
model <- glm(health ~age + health_lag + stock_lag+ Totalwealth_lag + Income_lag + medicaldebt_lag,family=binomial(link='logit'), data=df)
summary(model)
  
fitted.results <- predict(model,newdata=subset(df,select=c(1,3,4,5,6,7)),type='response')
fitted.results <- ifelse(fitted.results > 0.5,1,0)
misClasificError <- mean(fitted.results != df$health)
print(paste('Accuracy',1-misClasificError))

library(caret)
library(formattable)
cm_lasso<-confusionMatrix(data = factor(fitted.results),reference = as.factor(y), positive="1")

truth_predicted<-data.frame(obs=y,pred=fitted.results)%>%
  mutate(obs=case_when(obs=="0"~"Good",TRUE~"Bad"), pred=case_when(pred=="0"~"Good",TRUE~"Bad"))%>%
  mutate(obs=as.factor(obs),pred=as.factor(pred))
cm <- conf_mat(truth_predicted, obs, pred)
autoplot(cm, type = "heatmap",text.size=18) +
  scale_fill_gradient(low="#D6EAF8",high = "#2E86C1") +
  theme(text = element_text(size=18))



library(corrplot)
df1<-temp%>%
  group_by(HHIDPN)%>%
  arrange(HHIDPN,age)%>%
  na.omit()%>%
  mutate(health_lag=lag(health), stock_lag = lag(stock), Totalwealth_lag=lag(Totalwealth), Income_lag=lag(Income),medicaldebt_lag=lag(medicaldebt))%>%
  select(HHIDPN,age,health,health_lag,stock_lag,Totalwealth_lag,Income_lag,medicaldebt_lag)%>%
  na.omit()%>%
  ungroup(HHIDPN)%>%select(-HHIDPN)%>%
  filter(age>40 & age<50)%>%
  mutate(health=case_when(health<1~1,TRUE~0),health_lag=case_when(health_lag<1~1,TRUE~0))%>% ## unhealthy has lower score
  cor()
col<- colorRampPalette(c("red", "wheat3", "blue3"))(10)
#corrplot(cor(df%>%slice(1:5000)),method="number",type="lower",tl.col="black",col=col)
corrplot(df1,method="number",type="lower",tl.col="black",col=col)
 
```

## Merge of HRS and PSID data 
```{r}
HRS_helathdata<-read_csv("DV_HRS.csv")
psid_data<-readRDS('cse6242_PSID.rda')

Table_Age_Health_Wealth<-NULL
i<-1
temp <- HRS_helathdata%>%
 select(c(R1AGEY_B, deadyear2, paste('R',i,'SHLT',sep=''),paste('H',i,'ATOTF',sep=''),
          paste('H',i,'ITOT',sep=''), paste('H',i,'ATOTA',sep=''), paste('H',i,'ASTCK',sep=''),
          paste('H',i,'AHOUS',sep=''), HHIDPN))%>%
 dplyr::rename("age"="R1AGEY_B",
               "Health"=paste('R',i,'SHLT',sep=''),
               "NonhousingFinancialWealth"=paste('H',i,'ATOTF',sep=''),
               "Income" = paste('H',i,'ITOT',sep=''),
               "Totalwealth" = paste('H',i,'ATOTA',sep=''),
               "Equity" = paste('H',i,'ASTCK',sep=''),
               "Houseequity" = paste('H',i,'AHOUS',sep='')
               ) %>%
    mutate(age = age  + (i-1)*2, health = case_when(Health<=3~0,TRUE~1),
           default=case_when(deadyear2<=(1992+2*(i-1))~1,TRUE~0), "medicaldebt" = NaN)%>%
  select(age, default, health, HHIDPN,NonhousingFinancialWealth,Income,Totalwealth,Equity,Houseequity,medicaldebt)
Table_Age_Health_Wealth <-rbind(Table_Age_Health_Wealth, temp)
for (i in 2:13){
  temp <- HRS_helathdata%>%
   select(c(R1AGEY_B, deadyear2, paste('R',i,'SHLT',sep=''),paste('H',i,'ATOTF',sep=''),
            paste('H',i,'ITOT',sep=''), paste('H',i,'ATOTA',sep=''), paste('H',i,'ASTCK',sep=''),
            paste('H',i,'AHOUS',sep=''), paste('R',i,'OOPMD',sep=''), HHIDPN))%>%
   dplyr::rename("age"="R1AGEY_B",
                 "Health"=paste('R',i,'SHLT',sep=''),
                 "NonhousingFinancialWealth"=paste('H',i,'ATOTF',sep=''),
                 "Income" = paste('H',i,'ITOT',sep=''),
                 "Totalwealth" = paste('H',i,'ATOTA',sep=''),
                 "Equity" = paste('H',i,'ASTCK',sep=''),
                 "Houseequity" = paste('H',i,'AHOUS',sep=''),
                 "medicaldebt" = paste('R',i,'OOPMD',sep='')
                 ) %>%
      mutate(age = age  + (i-1)*2, health = case_when(Health<=3~0,TRUE~1),
             default=case_when(deadyear2<=(1992+2*(i-1))~1,TRUE~0))%>%
    select(age, default, health, HHIDPN,NonhousingFinancialWealth,Income,Totalwealth,Equity,Houseequity,medicaldebt)
  Table_Age_Health_Wealth <-rbind(Table_Age_Health_Wealth, temp)
}

temp<-Table_Age_Health_Wealth%>%
  dplyr::rename(financialwealth=NonhousingFinancialWealth, stock=Equity,labor=Income)%>%
  select(age,health,stock,medicaldebt, Houseequity,Totalwealth,labor)

temp2<-psid_data%>%
  mutate(health=case_when(health<=3~0,TRUE~1))%>%
  mutate(Totalwealth = financialwealth+house, Houseequity=house)%>%
  select(age,health,stock,medicaldebt,Houseequity,Totalwealth,labor)

df<-rbind(temp,temp2)

write.csv(df,file="HRS_PSID_OnlyFinancialvariables_Merge.csv",row.names=FALSE)
```

## Animate
```{r}
psid_data<-readRDS("cse6242_PSID.rda")
library(gganimate)
theme_set(theme_bw())
library(gifski)
df<-psid_data%>%
  mutate(health=case_when(health<=3~0,TRUE~1))%>%
  filter(age>=20, age<=95)%>%
  select(age,state,health) %>%
  group_by(age,state)%>%
  summarise(N=sum(!is.na(health)),badN=sum(health,na.rm=TRUE))%>%
  mutate(Bad = badN/N, Good=1-Bad)%>%
  ungroup(age,state)%>%
  select(age,state,Bad,Good)%>%
  gather(key,value,-age,-state)%>%
  mutate(state=as.factor(state))%>%
  group_by(age,state)
  
FIPS<-read.csv("~/Dropbox/Chen Yingshan/House_ChenYinshan/Empirical Literature/FIPS_state_code.csv")
FIPS<-FIPS%>%
  plyr::rename(c("FIPS"="state"))%>%
  mutate(state=as.factor(state))
df1<-df%>%
  left_join(FIPS,by=c("state"))%>%
  na.omit()

p<-ggplot(df1,aes(x=key, y=value*100, colour=as.factor(State))) +
  geom_point(alpha = 0.7) +
  scale_color_viridis_d() +
  scale_size(range = c(2, 12))+
  labs(x="Health status (by state)", y="Population Percent") +
  theme(legend.text = element_text(size=10))+
  # facet_wrap(~health) +
  #transition_time(age) +
  transition_states(age, transition_length = length(unique(df$age)), state_length = 1) +
  enter_fade() +
  exit_fade() +
  labs(title = "Age: {closest_state}") 
animate(p, duration = 20, fps = 10, width = 800, height = 500, renderer = gifski_renderer())
anim_save("region_age_health_percent2.gif")

```

